__name__ = 'bsync'
__title__ = 'Sync files on your computer to Box.com'
__version__ = '1.0.1'
__author__ = 'Justin Quick'
__author_email__ = 'jquick@stsci.edu'
__url__ = 'https://github.com/spacetelescope/bsync'
__license__ = 'APACHE 2'
__description__ = 'Sync files from your computer to Box.com using the Box API. Think rsync for Box.com'
